### ISSUE TITLE
Missing PP Elements

### ISSUE THREAD

**Issue by VanillaUI** [Baertram/PerfectPixel#6]
Hello. Thanks for your addon.
I found that some UI elements still dont have PP style.
Any plans of adding them in future ? 

List:
1. Magicka/Health/Stamina Bars
2. XP (progress) bar
3. Magicka/Health/Stamina bars in Character Stats Window
4. Target Health Bar
5. Minimized Char Frame (the thing with notifications near the chat)

**Comment by Baertram** [comment]
[About attribute and target bars]
PP's bars currently only use blue as color and they are used for progress bars, no attributes. Replacing them with PP style is not easily doable (and especially not for the attribute bars in general which always change their size and style -> with shields, heals etc.).
So currently not doable, without having to reinvent a lot (and I'm missing the time for that sorry).

[XP (progress) bar]
Klisk tried that already and it got many issues as the bar is used for multiple different xp bars, and thus it needs to override all of them. That's very tricky and does not look good. I cannot work on this at the moment, sorry.

[Minimized Chat Frame (the thing with notifications near the chat)]
Added, download here from Github the most current version and test it please @VanillaUI
